### ISSUE TITLE
Some fields are emptied on translate

### ISSUE THREAD

**Issue by genox** [r1tsuu/payload-enchants#22]
Hi,

I have a rather complex collection structure. I can post it here if you would like to test.

This is what I do:

1. Create new entry in base lang
2. Switch to secondary lang
3. "Copy from other locale"
4. Choose base lang
5. Press "Copy all"

Similarly, when I use "AI Translate":

1. Create new entry in base lang
2. Switch to secondary lang
3. "AI Translate"
4. Choose base lang
5. Press "Translate all"

=> All fields in an array structure that were previously containing text are now empty, including those marked as `localised: true`. Number fields seem to be unaffected by this.

When I reload the page, the fields contain the values they should contain.

Could it be that arrays are not handled yet?

**Comment by r1tsuu** [comment]
All fields should work, can you give me the config of your array field so i can check?

**Comment by r1tsuu** [comment]
Okay, i just checked with latest Payload 3.0 and it doesn't work with array field.
I'm gonna quickly fix that, seems like change in Payload caused it.

**Comment by r1tsuu** [comment]
Hi! Fixed this issue and as well updated this repo https://github.com/r1tsuu/payload-enchants because i want to write more packages/plugins i maintain the same repo.
translator docs - https://github.com/r1tsuu/payload-enchants/tree/master/packages/translator
there's only 1 breaking change that you need to change import a bit.
`pnpm add @payload-enchants/translator`

**Comment by genox** [comment]
Seems to work fine now, however I get an error when using the openAI translator now. It complains about receiving null instead of an array.

**Comment by r1tsuu** [comment]
> Seems to work fine now, however I get an error when using the openAI translator now. It complains about receiving null instead of an array.

i can't reproduce it 
https://github.com/r1tsuu/payload-enchants/assets/64744993/ed49ceda-2bd9-46b5-90ad-ff732f84e26d

are you getting this error every time or sometimes? i can see that ChatGPT isn't consistent in responses causes to invalid structure, even though my prompt is clear.

**Comment by genox** [comment]
I get the error every time I hit the translation button. It worked before you moved to mono repo. Maybe my config is off.

```sh
[13:19:15] INFO:
    data: null
    message: "An error occurred when trying to translate the data using OpenAI API - parsed content is not an array"
 POST /api/translator/translate 200 in 1169ms

```

**Comment by genox** [comment]
@r1tsuu Hi again

I had some time to look into it and it seems that one of the source fields has a `null` value which is translated to `null` and therefore causes an error while parsing the response as it specifically parses for `typeof string`.

I think it is safe to assume that `null` (and `boolean` values or purely numerical values?) should not be sent as part of the translation request, even though they end up in a text field - it could be an error on the side of the integrator that builds a schema wrongly or a component that nulls something. It would also add to the resilience of the translation function to handle such cases gracefully, e.g. by notification about the fact that there is an unexpected value present that might not be intended.

**Comment by siobahnschuck** [comment]
I was running into the same `null` error. This was occuring for me when content that had `localized: true` set in the schema but was not required field was left empty. Instead of saving as an empty string the data returns null. I fixed this by updating the condition for strings in `packages/translator/src/resolvers/openAI.ts` line 121:

` if (text !== null && typeof text !== 'string')`

**Comment by genox** [comment]
This should be resolved now. Thank you!

**Comment by r1tsuu** [comment]
> This should be resolved now. Thank you!

Just to know, released one more after this https://github.com/r1tsuu/payload-enchants/releases/tag/1.1.32 
there was an issue that you couldn't save the doc after translate as it wasn't modified
