### ISSUE TITLE
Better Localised Fields plugin hides sidebar, doesn't play well with conditional fields

### ISSUE THREAD

**Issue by genox** [r1tsuu/payload-enchants#38]
Hi,

I gave this one a spin too and found some issues:

- Using the plugin makes the sidebar disappear and all fields rendered in the main column (sidebar as in `admin: {position: 'sidebar'}`). There are no translatable fields in the sidebar.
- The tabs are rendered, even though the attached field is conditionally hidden (`admin: { condition: ()=>false}`)

Thank you!

**Comment by r1tsuu** [comment]
thank you, i haven't tested these cases, will look into this.

**Comment by r1tsuu** [comment]
Fixed in the latest release.

**Comment by genox** [comment]
thank you
