### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by digitaledge-git** [r1tsuu/payload-enchants#97]
Hi there,

First off, I want to say the translation plugin was fantastic—great work on it! Unfortunately, it no longer works with Payload 3.0.0. I wanted to check if this repository is still being actively developed or maintained.

Looking forward to hearing from you. Thanks in advance!

**Comment by r1tsuu** [comment]
Just released 1.3.0! https://github.com/r1tsuu/payload-enchants/releases/tag/translator-1.3.0
